spring:
  application:
    name: NulDormitoryManager-Backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nul_dorm_manager
    username: nullsty
    password: sty@20030209
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl